# PUT http://localhost:3101/api/updatecategory/652cefc663603fda07747a2b
# Content-Type : application/json

# {
#     "nameCategory":"laptop1",
#     "description":""
# }
POST http://localhost:3101/api/auth/login/admin
Content-Type: application/json

{
    "accountName":"admin2",
    "password":"admin"   
}
