
# PUT http://localhost:3101/api/brands/update/653b7e0d83182db56054de0c
# content-type: application/json

# {
#     "nameBrand": "Tai nghe của Anh Độ ",
#     "description": "Mô tả thương hiệu",
#     "status": "Active"
# }


# GET http://localhost:3101/api/brands/get/6536401ff03a61e84e773f45

# GET http://localhost:3101/api/catalog/getlistcateandbrand

# post http://localhost:3101/api/brands/add
# content-type: application/json

# {
#     "nameBrand": "Tai nghe Lúc nhúc ",
#     "description": "Mô tả thương hiệu",
#     "category":"653b7dce83182db56054de09",
#     "status": "Active"
# }
# Get http://localhost:3101/api/brands/getall

# Get http://localhost:3101/api/categories/getall

# POST http://localhost:3101/api/categories/add
# content-type: application/json

# {
#     "nameCategory": "Tai Nghe",
#     "description": "Mô tả danh mục",
#     "status": "Active"
# }

# POST http://localhost:3101/api/products/add
# content-type: application/json

# {
#     "nameProduct": "Iphone 13",
#     "description": "Mô tả sản phẩm",
#     "price": 10000000,
#     "oldprice": 11000000,
#     "imges":["uploads/1698257578682-chandung.jpg"],
#     "status": "Active",
#     "category": "65394a3501cc7134c7daa57d",
#     "brand": "65394f137fb869aad55653af"
# # 
Post http://localhost:3101/api/auth/register/admin
content-type: application/json

{
    "accountName": "admin20",
    "password": "admin"
}

