export { default as RegisterFrom } from './auth/RegisterFrom';
export { default as LoginForm } from './auth/LoginForm';
export { default as BannerTop } from './homepage/BannerTop';
export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as BannerSales } from './homepage/BannerSales';
export { default as BlogSection } from './homepage/BlogSection';
export { default as BannerScroll } from './homepage/BannerScroll';
export { default as SloganListSection } from './homepage/SloganListSection';
export { default as ProductList } from './homepage/ProductList';
export { default as ProductSlide } from './homepage/ProductSlide';
export {default as Breadcrumb} from './collection/Breadcrumb' ;